- .devcontainer/devcontainer.json
- README.md
Update devcontainer (we have a vscode extension !). Update readme with notes and warnings
> Minor fixes to readme

- modules/nf-scil/denoising/mppca/main.nf
- modules/nf-scil/denoising/mppca/meta.yml
- tests/config/pytest_modules.yml
- tests/config/test_data.config
- tests/modules/nf-scil/denoising/mppca/main.nf
- tests/modules/nf-scil/denoising/mppca/nextflow.config
- tests/modules/nf-scil/denoising/mppca/test.yml
creation of the dwi denoising module, I didn't add all the option.
both tests worked and the data used are those from the normalization test.
> add module denoising/mppca

- modules/nf-scil/utils/extractb0/main.nf
- modules/nf-scil/utils/extractb0/meta.yml
- tests/config/pytest_modules.yml
- tests/config/test_data.config
- tests/modules/nf-scil/utils/extractb0/main.nf
- tests/modules/nf-scil/utils/extractb0/nextflow.config
- tests/modules/nf-scil/utils/extractb0/test.yml
Add a utility module to extract b0 volumes
Data in `.test_data/heavy/dwi`
> Add extractb0 module

- .devcontainer/Dockerfile
- .devcontainer/setup_container.sh
- .github/workflows/checks.yml
- .github/workflows/test_module.yml
- modules/nf-scil/tracking/localtracking/main.nf
- modules/nf-scil/tracking/pfttracking/main.nf
- tests/modules/nf-scil/tracking/localtracking/nextflow.config
- tests/modules/nf-scil/tracking/localtracking/test.yml
> Fixes for workflows on singularity

- modules/nf-scil/testdata/scilpy/main.nf
Add test data for registration
> Add registration archive

- .github/workflows/test_module.yml
- modules/nf-scil/testdata/scilpy/main.nf
Add archive links for `bids` and `antsbet`, and update `eddy_topup`.
> Update test data

- modules/nf-scil/testdata/scilpy/main.nf
Bids data needs to be in a folder
> Update bids archive

- modules/nf-scil/testdata/scilpy/main.nf
> Update antsbet archive

- poetry.lock
- pyproject.toml
Bad requirement listing in `pyproject.toml`
Build the current devcontainer
> Fix poetry environment

- modules/nf-scil/register/anattodwi/main.nf
- modules/nf-scil/register/anattodwi/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-scil/register/anattodwi/main.nf
- tests/modules/nf-scil/register/anattodwi/nextflow.config
- tests/modules/nf-scil/register/anattodwi/test.yml
Added module to register an anatomical image on a diffusion image using a b0 and a metric (fa). 
Uses data from scilpy's processing folder
> [Module] Anat to DWI registration

- modules/nf-scil/preproc/n4/main.nf
- modules/nf-scil/preproc/n4/meta.yml
- tests/modules/nf-scil/preproc/n4/main.nf
- tests/modules/nf-scil/preproc/n4/nextflow.config
- tests/modules/nf-scil/preproc/n4/test.yml
modification of the N4 module to process the T1 image and renaming of inputs and outputs to make them more generic.
> Add option T1 for N4 module

- modules/environment-schema.json
Add environment schema for nf-core update (so modules lint correctly).
> Add environment schema file for linting

- .github/workflows/nf-test_module.yml
`setup-nf-test` was targeting the `main` on my fork. I switched to a specific commit hash, since the `main` is required to change for PR on the official action.
> Fix setup-nf-test version

- modules/nf-scil/testdata/scilpy/main.nf
**If submitting a new module or fixing a bug, please use the appropriate template.**
Move legacy `test_data` content to `DVC`. Have not removed the directory yet, @gagnonanthony will make the changes in is various `nf-test` transition PRs.
> [TEST] Move .test_data content to dvc

- modules/nf-scil/tractogram/removeinvalid/environment.yml
- modules/nf-scil/tractogram/removeinvalid/main.nf
- modules/nf-scil/tractogram/removeinvalid/meta.yml
- modules/nf-scil/tractogram/removeinvalid/tests/main.nf.test
- modules/nf-scil/tractogram/removeinvalid/tests/main.nf.test.snap
- modules/nf-scil/tractogram/removeinvalid/tests/nextflow.config
- modules/nf-scil/tractogram/removeinvalid/tests/tags.yml
Add a remove invalid streamlines module to later include it in a tractometry subworkflow. 
- `bundles.zip`
> [Module] Remove invalid streamlines module. 

- modules/nf-scil/bundle/labelmap/main.nf
- modules/nf-scil/bundle/labelmap/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-scil/bundle/labelmap/main.nf
- tests/modules/nf-scil/bundle/labelmap/nextflow.config
- tests/modules/nf-scil/bundle/labelmap/test.yml
WIP - testing not done
Added the module `BUNDLE_LABEL_AND_DISTANCE_MAP`
> [Module][WIP] bundle labelmap

- .github/workflows/checks.yml
- .github/workflows/update_pr.yml
Fix workflow run on push to main.
Provide a full step-by-step guide to reproduce the bug.
> add merge group and fix refs for direct push to master

- modules/nf-scil/image/applymask/environment.yml
- modules/nf-scil/image/applymask/main.nf
- modules/nf-scil/image/applymask/meta.yml
- modules/nf-scil/image/applymask/tests/main.nf.test
- modules/nf-scil/image/applymask/tests/main.nf.test.snap
- modules/nf-scil/image/applymask/tests/tags.yml
Add image/applymask module working on 3D and 4D images. Useful to apply a BET on a 4D volume. 
- heavy.zip (dwi, mask (dwi), anat, and mask(anat))
> [Module] Add image/applymask module.

- modules/nf-scil/image/powderaverage/environment.yml
- modules/nf-scil/image/powderaverage/main.nf
- modules/nf-scil/image/powderaverage/meta.yml
- modules/nf-scil/image/powderaverage/tests/main.nf.test
- modules/nf-scil/image/powderaverage/tests/main.nf.test.snap
- modules/nf-scil/image/powderaverage/tests/nextflow.config
- modules/nf-scil/image/powderaverage/tests/tags.yml
New module to compute the powder average of a DWI volume. Needed for my pediatric pipeline.
- heavy.zip (dwi, bval, and mask)
> [Module] Add image/powderaverage module

- .github/workflows/checks.yml
- .github/workflows/nf-test_module.yml
**If submitting a new module or fixing a bug, please use the appropriate template.**
Add an option to configure a test workflow's runner. The bigmem runner is already up and waiting for jobs.
@ThoumyreStanislas rebase your Easyreg branch on this (I can show you how) and push. It should trigger the right runner config for your tests.
> Add runner with a lot of RAM for ML tests

- .github/workflows/review_assignment.yml
Still no permission to add the reviewers. This should fix it.
> Grant access to secrets

- .github/reviewers.yml
Pre-generated templates are available for most types of PR :
- [New module](.github/PULL_REQUEST_TEMPLATE/new_module.md)
- [Bugfix](.github/PULL_REQUEST_TEMPLATE/bugfix.md)
- [Improvement](.github/PULL_REQUEST_TEMPLATE/improvement.md)
You can simply copy the content of the template and paste it in the description of your PR. Then, fill the sections with the appropriate information.
You can also use the `html query parameter` to preload the template in the PR description. For example, to preload the `bugfix` template, suffix your current url with `?template=bugfix.md` and press `Enter`. The template will be loaded in the description of your PR.
> Fix reviewers list based on current issues and PRs

- .github/reviewers.yml
> [FIX] Remove all teams and fix group enabling
